version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Exposes port 3000 on host to port 80 in the container
    container_name: react-app-container
    restart: always

